### ISSUE TITLE
Multiple matches on same day work around?

### ISSUE THREAD

**Issue by mpentrack** [jtfeld/EloOptimized#1]
I tried entering a dataset that had a few teams play multiple matches on the same day and it appears to break the code as I changed some of the dates on the NBA dataset and got the same error. Is there any work around to get this to work without manually changing the dates or deleting the entries entirely?

Thanks, great package.

**Comment by jtfeld** [comment]
Hey, could you provide some more info on this?  What OS and version of R are you using?  What were the errors you got?  Did the error occur when one team played multiple matches (any opponent) on one day or when two teams played each other multiple times on one day?  I just added redundant rows to the nba data set and didn't encounter any problems.
