### ISSUE TITLE
Error executing function elo.m3_lik_vect

### ISSUE THREAD

**Issue by Dhiordan** [jtfeld/EloOptimized#2]
When executing the function elo.m3_lik_vect(par, IA_data, all_ids) happens the following error
 "Error in par [1]:
   object of closure type can not be split into subsets" 
could you advise me how to fix this?

**Comment by jtfeld** [comment]
That's meant to be an internal function, so the eloratingopt or eloratingfixed wrapper functions ensure that the data being processed are of the right format.  My guess is that you're providing the function with the wrong sort of data.  Is there a reason you're trying to run that function outside of the wrapper function?
