### ISSUE TITLE
error with dates? 

### ISSUE THREAD

**Issue by ioannis12** [jtfeld/EloOptimized#3]
I run the eloratingopt and eloratingfixed functions in a dataset with the required format but keep on getting the following error message: 

> Error in eloratingopt(agon_data = Data, fit_init_elo = FALSE) : 
>   some start dates are later than end dates. ID's with this problem:

any ideas?

**Comment by jtfeld** [comment]
The idea is that if your presence data set contains any start dates that are after the corresponding end date(s), the code catches that and returns an error.  Did you check your presence data set to see if, for any individuals, the start date is later than the end date?
